### ISSUE TITLE
Phantom Trials

### ISSUE THREAD

**Issue by maia-sh** [bgcarlisle/Numbat#35]
@bgcarlisle ,

I'm realizing that we have some phantom trials, of a few varieties, and I'm concerned...

1. Trials that appear in the extractions but not in the assignments, e.g. "tri02225" with trial id "EUCTR2020-001536-98"
2. Trials that appear "not yet started" instead of "in progress" (all trials should be "in progress" because I upload extractions to pre-fill in some data) and are not prepopulated with the extraction. E.g., tri01919 (NCT04378712) [which I since completed and marked as complete], tri03365 (NCT04371822) [which Molly and I since marked as complete], tri01097, tri01560, tri05392, ... 

These also sometimes have something odd happening with the titles looking cutoff and the internal trial id not displaying, e.g., trial id "CTRI/2020/06/026087 (CTRI)":
![Screen Shot 2021-07-07 at 17 38 04](https://user-images.githubusercontent.com/38968656/124788903-18b4ad00-df4a-11eb-9083-61ef643583bd.png)
![Screen Shot 2021-07-07 at 17 37 48](https://user-images.githubusercontent.com/38968656/124788864-0e92ae80-df4a-11eb-91fa-9aa6d1cae983.png)
3. Some other columns appearing as trials...
![Screen Shot 2021-07-07 at 17 38 34](https://user-images.githubusercontent.com/38968656/124788985-2a965000-df4a-11eb-9194-912dadb3b407.png)
![Screen Shot 2021-07-07 at 17 38 57](https://user-images.githubusercontent.com/38968656/124789044-371aa880-df4a-11eb-99d9-7dc04d61177f.png)

**Comment by maia-sh** [comment]
I'm thinking this might be a TSV parsing issue happening moving between R and Numbat.  Have you had any similar issues at this interface? I also get wonkiness when I read out from Numbat. E.g.,

```
readr::read_tsv("https://numbat.bgcarlisle.com/direcct/export/2021-07-01_051126-sub_registrations-refset_26-sub-extraction.tsv")
```

Give me this warning:

── Column specification ───────────────────────────────────────
cols(
  .default = col_character(),
  id = col_double(),
  manual = col_double(),
  year = col_logical(),
  journal = col_logical(),
  abstract = col_logical(),
  id_1 = col_double(),
  refsetid = col_double(),
  referenceid = col_double(),
  userid = col_double(),
  sortorder = col_double()
)
ℹ Use `spec()` for the full column specifications.

Warning: 48208 parsing failures.
 row   col           expected actual                                                                                                            file
1091 title delimiter or quote      P 'https://numbat.bgcarlisle.com/direcct/export/2021-07-01_051126-sub_registrations-refset_26-sub-extraction.tsv'
1091 title delimiter or quote      P 'https://numbat.bgcarlisle.com/direcct/export/2021-07-01_051126-sub_registrations-refset_26-sub-extraction.tsv'
1091 title delimiter or quote      P 'https://numbat.bgcarlisle.com/direcct/export/2021-07-01_051126-sub_registrations-refset_26-sub-extraction.tsv'
1091 title delimiter or quote      P 'https://numbat.bgcarlisle.com/direcct/export/2021-07-01_051126-sub_registrations-refset_26-sub-extraction.tsv'
1091 title delimiter or quote      h 'https://numbat.bgcarlisle.com/direcct/export/2021-07-01_051126-sub_registrations-refset_26-sub-extraction.tsv'
.... ..... .................. ...... ............................................. [... truncated]
Warning message:
Duplicated column names deduplicated: 'id' => 'id_1' [16]

**Comment by bgcarlisle** [comment]
When you say "Trials that appear in the extractions but not in the assignments" what do you mean by "appear in the extractions"?

When you import extractions, you can set the status of the extractions using the Status drop-down menu (last one before "Import extractions"):

![image](https://user-images.githubusercontent.com/3100614/124791866-74674200-df1a-11eb-8a3e-8b1495669b28.png)

If you left this as "Not yet started", it wouldn't be automatically set to "In progress"

Do you have the TSV you used to upload? It looks like there's some sort of parsing issue there

**Comment by maia-sh** [comment]
> When you say "Trials that appear in the extractions but not in the assignments" what do you mean by "appear in the extractions"?

In https://numbat.bgcarlisle.com/direcct/export/2021-07-01_051126-sub_registrations-refset_26-sub-extraction.tsv, "tri02225" appears but I'm not seeing it on the assignment page when I ctrl+f for it.

**Comment by maia-sh** [comment]
> When you import extractions, you can set the status of the extractions using the Status drop-down menu (last one before "Import extractions"):

Yes, I did this. It's step 24 on my upload instructions ;)

```
17. Navigate to `Import extractions`: https://numbat.bgcarlisle.com/direcct/extract/?action=import
18. Under `Use the following reference set`, select the batch you have just created.
19. Under `Use the following form`, select `Results Search`
20. Check that `Attribute all of the imported extractions to the following user` is assigned to the default `Attribute imported extractions to user by column value`
21. Click `Choose File` or drag-and-drop `trials.tsv`
22. Click `Upload extractions`
23. Confirm that each Numbat variable is correctly assigned to each variable in the uploaded file. Note that these should automatically match, but should be corrected if incorrect or assigned as `Leave blank`. Some variables do not exist in the uploaded file and should be left as `Leave blank`.
24. Change `Status` to `In progress`.
25. Click `Import extractions`
26. Repeat steps 18-25 for:
    1. `-- Add trial registrations from registry or publications (sub-extraction)` with `registrations.tsv`
    2. `-- Add results (sub-extraction)` with  `results.tsv`
    3. `-- Keyword Search Strings (table)`
27. Navigate to `Manage extraction assigments`: https://numbat.bgcarlisle.com/direcct/assignments/
28. Click `View` on the batch you have just created.
29. Assign coders
25. Navigate to `Do extractions`: https://numbat.bgcarlisle.com/direcct/extract/
```

**Comment by bgcarlisle** [comment]
Okay so I have a theory about why the Numbat export is wonky

There's an unmatched quotation mark in one of the titles (`Prophylaxis of COVID-19 infection with hydroxychloroquine in healthcare` was `"Prophylaxis of COVID-19 infection with hydroxychloroquine in healthcare`)

I've removed this; try exporting again to generate a new link?

**Comment by maia-sh** [comment]
> Do you have the TSV you used to upload? It looks like there's some sort of parsing issue there

I'll email you as a zip since it's several files because of the sub extractions, etc.

**Comment by maia-sh** [comment]
> Okay so I have a theory about why the Numbat export is wonky
> 
> There's an unmatched quotation mark in one of the titles (`Prophylaxis of COVID-19 infection with hydroxychloroquine in healthcare` was `"Prophylaxis of COVID-19 infection with hydroxychloroquine in healthcare`)
> 
> I've removed this; try exporting again to generate a new link?

That fixed a bunch of parsing failures but there are still some.

```
> registrations_raw <- read_tsv("https://numbat.bgcarlisle.com/direcct/export/2021-07-07_091715-sub_registrations-refset_26-sub-extraction.tsv")

── Column specification ──────
cols(
  .default = col_character(),
  id = col_double(),
  manual = col_double(),
  year = col_logical(),
  journal = col_logical(),
  abstract = col_logical(),
  id_1 = col_double(),
  refsetid = col_double(),
  referenceid = col_double(),
  userid = col_double(),
  sortorder = col_double()
)
ℹ Use `spec()` for the full column specifications.

Warning: 46506 parsing failures.
 row      col           expected actual                                                                                                            file
1091 year     1/0/T/F/TRUE/FALSE   NULL 'https://numbat.bgcarlisle.com/direcct/export/2021-07-07_091715-sub_registrations-refset_26-sub-extraction.tsv'
1091 journal  1/0/T/F/TRUE/FALSE   NULL 'https://numbat.bgcarlisle.com/direcct/export/2021-07-07_091715-sub_registrations-refset_26-sub-extraction.tsv'
1091 abstract 1/0/T/F/TRUE/FALSE   NULL 'https://numbat.bgcarlisle.com/direcct/export/2021-07-07_091715-sub_registrations-refset_26-sub-extraction.tsv'
1092 year     1/0/T/F/TRUE/FALSE   NULL 'https://numbat.bgcarlisle.com/direcct/export/2021-07-07_091715-sub_registrations-refset_26-sub-extraction.tsv'
1092 journal  1/0/T/F/TRUE/FALSE   NULL 'https://numbat.bgcarlisle.com/direcct/export/2021-07-07_091715-sub_registrations-refset_26-sub-extraction.tsv'
.... ........ .................. ...... ........................ [... truncated]
Warning message:
Duplicated column names deduplicated: 'id' => 'id_1' [16] 
```

**Comment by bgcarlisle** [comment]
Changed:

* `"Efficacy of AYUSH-64 (a polyherbal formulation) in COVID - 19 Cases` to `"Efficacy of AYUSH-64 (a polyherbal formulation) in COVID - 19 Cases`
* `"Phase II, randomized, controlled, open-label study of` to `Phase II, randomized, controlled, open-label study of`
* `"A Study on Unani regimen` to `A Study on Unani regimen`

This should fix a bunch more of the errors

Also, if you add `na=c("", "NA", "NULL")` as an argument to `read_tsv()`, that should fix another one

Try generating a new link and trying again!

**Comment by maia-sh** [comment]
Hi @bgcarlisle ! Thanks for all these edits. Unfortunately, still get parsing errors, and still not able to figure out why.
`read_tsv("https://numbat.bgcarlisle.com/direcct/export/2021-08-06_091152-form_5-refset_26-final.tsv")` gives 11 errors.
`read_tsv("https://numbat.bgcarlisle.com/direcct/export/2021-08-06_091152-form_5-refset_26-final.tsv", na=c("", "NA", "NULL"))` gives 34 errors.

Do you think these are all coming from titles? If so, maybe you can delete the title field in the numbat backend? I can then fix it in R and then you can add the cleaned titles? Is that technically possible? And if so, what do I need to remove from titles? Quote marks I see for sure.

Or do you have another suggestion? I need to be able to read them into R to analyze them and I'm worried if I just ignore these failures there will be a silent bug...

**Comment by maia-sh** [comment]
This is also likely related, so I'm mentioning here. 4 trials have "full search" as a title and have the data all off. The screenshots are from the assignment page

https://www.clinicaltrialsregister.eu/ctr-search/search?query=eudract_number:2020-001536-98:
![Screen Shot 2021-08-06 at 18 19 15](https://user-images.githubusercontent.com/38968656/128541178-8a1ddd80-d6b4-40bd-b88d-53c9378f8202.png)

http://www.ctri.nic.in/Clinicaltrials/pmaindet2.php?trialid=43949:
![Screen Shot 2021-08-06 at 18 19 44](https://user-images.githubusercontent.com/38968656/128541254-5ea2db47-f3cc-4c39-8d81-7dbd1bbc8d31.png)

http://www.ctri.nic.in/Clinicaltrials/pmaindet2.php?trialid=43775:
![Screen Shot 2021-08-06 at 18 20 11](https://user-images.githubusercontent.com/38968656/128541331-0a919619-a51a-4b5f-b17d-be6d6a15485b.png)

http://www.ctri.nic.in/Clinicaltrials/pmaindet2.php?trialid=44584:
![Screen Shot 2021-08-06 at 18 20 26](https://user-images.githubusercontent.com/38968656/128541355-48f8d036-4168-4c4d-8e4b-eb03fe26d031.png)

**Comment by bgcarlisle** [comment]
I fixed the export of "Cutoff 2"

https://numbat.bgcarlisle.com/direcct/export/2021-08-08_235528-form_5-refset_26-final.tsv

There were double quotes in the extracted data, so I replaced them with single quotes

So, short term solution: avoid double quotes

Long term solution: I'll write something into the exporter so that in subsequent versions of Numbat this doesn't happen again

**Comment by bgcarlisle** [comment]
(For future reference)

I found the problems in the reference set, and they occurred because the titles included returns that broke the importer

These have been fixed in the database and I have made a note to update the importer so that this does not occur again!
