### ISSUE TITLE
Bug: Numbat Export for sub-extraction and table

### ISSUE THREAD

**Issue by maia-sh** [bgcarlisle/Numbat#38]
Hi @bgcarlisle , putting this issue here to not get lost.
Thanks for all the help with the main extractions - those are working beautifully now!
Unfortunately, I'm still having trouble with the subextractions and tables for both extractions and reconciled/final.

Here's a video: https://www.loom.com/share/90ddf3afa4494a4eb5a58efe18f6c2cc

Thanks for your help!

**Comment by maia-sh** [comment]
There's also still an issue with the extractions for the main extraction. `team_review` should be TRUE or NULL, however for 10 trials it has free text which I believe should be in `comments`: `distinct(extractions, team_review)`

**Comment by bgcarlisle** [comment]
Okay so I redid the exporter to fix some weirdo bugs

Want to try exporting again and tell me if these problems persist?

**Comment by maia-sh** [comment]
Just checked and still got a problem:

`readr::read_tsv("https://numbat.bgcarlisle.com/direcct/export/2021-09-21_003442-form_5-refset_26-extractions.tsv")`

```
Warning message:
One or more parsing issues, see `problems()` for details 
```

```
> problems()
# A tibble: 1 × 5
    row   col expected           actual file 
  <int> <int> <chr>              <chr>  <chr>
1  2322    18 1/0/T/F/TRUE/FALSE NULL   ""  
```

**Comment by maia-sh** [comment]
> There's also still an issue with the extractions for the main extraction. `team_review` should be TRUE or NULL, however for 10 trials it has free text which I believe should be in `comments`: `distinct(extractions, team_review)`

This is resolved :)

```
> extraction_trials %>% distinct(team_review)
# A tibble: 2 × 1
  team_review
  <chr>      
1 NULL       
2 TRUE  
```

**Comment by bgcarlisle** [comment]
Okay so the first one seems to be resolved if you tell R to read `NULL` values as `na`:

readr::read_tsv("https://numbat.bgcarlisle.com/direcct/export/2021-09-21_003442-form_5-refset_26-extractions.tsv", na = c("", "NA", "NULL"))

**Comment by bgcarlisle** [comment]
Lemme have a look at the second one ...

**Comment by maia-sh** [comment]
For reconciliation, still having the weird 0000 dates which is throwing off R as a problem. 

`readr::read_tsv("https://numbat.bgcarlisle.com/direcct/export/2021-09-21_003454-form_5-refset_26-final.tsv", na = c("", "NA", "NULL"))`

```
Warning message:
One or more parsing issues, see `problems()` for details 
```

```
> problems()
# A tibble: 25 × 5
     row   col expected        actual     file 
   <int> <int> <chr>           <chr>      <chr>
 1     2    21 date in ISO8601 0000-00-00 ""   
 2    10    21 date in ISO8601 0000-00-00 ""   
 3    16    21 date in ISO8601 0000-00-00 ""   
 4    17    21 date in ISO8601 0000-00-00 ""   
 5    18    21 date in ISO8601 0000-00-00 ""   
 6    22    21 date in ISO8601 0000-00-00 ""   
 7    23    21 date in ISO8601 0000-00-00 ""   
 8    24    21 date in ISO8601 0000-00-00 ""   
 9    25    21 date in ISO8601 0000-00-00 ""   
10    26    21 date in ISO8601 0000-00-00 ""   
# … with 15 more rows
```

**Comment by bgcarlisle** [comment]
Yeah the easy solution is:

`readr::read_tsv("https://numbat.bgcarlisle.com/direcct/export/2021-09-21_003454-form_5-refset_26-final.tsv", na = c("", "NA", "NULL", "0000-00-00"))`

However, I can remove them manually from the database if you like!

I'm also fixing Numbat so that reconciling an empty date no longer puts 0's in there

**Comment by bgcarlisle** [comment]
This should fix the bug, do you want me to go ahead and convert all the "0000-00-00" values to `NULL` in the database?

https://github.com/bgcarlisle/Numbat/commit/3f37bccda493e5c4d2ed5e2f97043b7785675970

**Comment by maia-sh** [comment]
> This should fix the bug, do you want me to go ahead and convert all the "0000-00-00" values to `NULL` in the database?
> 
> [3f37bcc](https://github.com/bgcarlisle/Numbat/commit/3f37bccda493e5c4d2ed5e2f97043b7785675970)

yes please! removing the 0000 would be great since they should be NULL
