### ISSUE TITLE
Bug: Phantom "-01"

### ISSUE THREAD

**Issue by maia-sh** [bgcarlisle/Numbat#42]
I'm getting a phantom "-01" during the reconciliation of  in [tri02060/NCT04390412 ](https://numbat.bgcarlisle.com/direcct/final/?action=reconcile&form=5&refset=26&ref=873) in “final enrollment date” for the result with doi 10.1016/j.ijrobp.2020.07.026. I have tried deleting but it simply comes back.

![Screen Shot 2021-08-27 at 13 33 43](https://user-images.githubusercontent.com/38968656/131121251-4965e643-9673-454e-9b5f-cda3a601af78.png)

**Comment by maia-sh** [comment]
Also for this trial: https://numbat.bgcarlisle.com/direcct/final/?action=reconcile&form=5&refset=26&ref=575
for doi: 10.1016/j.transci.2020.102922

**Comment by bgcarlisle** [comment]
This should fix it! https://github.com/bgcarlisle/Numbat/commit/11f4e0125c64e1e62f2769eb0d549769192a1d7c

**Comment by maia-sh** [comment]
Grand! Looks automatically fixed for the two trials I mentioned here:
https://numbat.bgcarlisle.com/direcct/final/?action=reconcile&form=5&refset=26&ref=575
https://numbat.bgcarlisle.com/direcct/final/?action=reconcile&form=5&refset=26&ref=873

However, I see these that issue #43 is still happening.
