### ISSUE TITLE
Feature request: Controlled vocabulary

### ISSUE THREAD

**Issue by maia-sh** [bgcarlisle/Numbat#48]
Hi Murph! I'm preparing another form to extract trial interventions, and Nick and I are trying to figure out how to allow users to capture all unique interventions, but also use consistent names for the same intervention. For example, all “chloroquine” trials would be coded as “chloroquine”, and  not as “chloroquine phosphate”, etc. But then if there's a new trial with say "green tea" users could capture that too. So a traditional "single select" doesn't work well, because then we have to pre-specify the interventions. Ideally, we would like to have coders put in an intervention which they gets added to the "controlled vocabulary" which they can then select from; and they can always add a new intervention to the vocabulary.

Definitely a far out feature request, but thought I'd share!

If you've done something like this intervention extraction before and have suggestions on how to best Numbat it, please let me know :)

**Comment by bgcarlisle** [comment]
May I recommend the "previously extracted entry selector"?

I think it will do what you're asking for!

https://user-images.githubusercontent.com/3100614/134160193-b30bdfdc-2d6f-4bd5-a53a-f88bcbc46e57.mp4

**Comment by bgcarlisle** [comment]
https://user-images.githubusercontent.com/3100614/135895873-e2f2f3ec-2e3e-4117-b66b-061015d3b225.mp4

Almost there!!
