### ISSUE TITLE
Bug: Empty reconciliation sub-extraction

### ISSUE THREAD

**Issue by maia-sh** [bgcarlisle/Numbat#56]
Somehow the reconciliation is empty (which it should not be):
`read_tsv("https://numbat.bgcarlisle.com/direcct/export/2021-10-08_042141-sub_result-refset_26-sub-final.tsv", na = c("", "NA", "NULL", "0000-00-00"), show_col_types = FALSE)`

The extraction comes through:
`read_tsv("https://numbat.bgcarlisle.com/direcct/export/2021-10-08_042228-sub_result-refset_26-sub-extraction.tsv", na = c("", "NA", "NULL", "0000-00-00"), show_col_types = FALSE)`

**Comment by bgcarlisle** [comment]
Okay try now?

dfc5b71910bef25e20d68dbcaa73e80096369033

**Comment by bgcarlisle** [comment]
Yayy!!
